FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY index.html vite.config.ts tsconfig.json ./
COPY src ./src
ENV NODE_ENV=development
ENV CHOKIDAR_USEPOLLING=true
EXPOSE 13011
CMD ["npm", "run", "dev", "--", "--port=3000"]
